[global]
keyboard = "en-us"
country = "us"
fqdn = "pve-temp.local"
timezone = "America/New_York"
root-password-hashed = "$6$GnEOkKKvgD8wEgQQ$ArxCjjXtfa6AGOFxs5dN.fjygr91WOxW1KPDyyGjsnvlWY7i1d1V9IKUlBjR075Ia9nY5esfC9MAnekCTmVPF0"

[network]
source = "from-answer"
cidr = "192.168.1.47/24"
dns = "1.1.1.1"
gateway = "192.168.1.254"

[disk-setup]
filesystem = "ext4"
filter = "size>450G AND size<600G AND removable=0 AND rotational=0"

[first-boot]
source = "from-url"
ordering = "network-online"
url = "https://raw.githubusercontent.com/buddy9880/pve-unattended-install/refs/heads/main/firstboot.sh"