[global]
mailto = "mail@no.invalid"
keyboard = "en-us"
country = "us"
fqdn = "pve-temp.local"
timezone = "America/New_York"
root-password-hashed = "$6$GnEOkKKvgD8wEgQQ$ArxCjjXtfa6AGOFxs5dN.fjygr91WOxW1KPDyyGjsnvlWY7i1d1V9IKUlBjR075Ia9nY5esfC9MAnekCTmVPF0"

[network]
source = "from-answer"
cidr = "192.168.1.47/24"
dns = "1.1.1.1"
gateway = "192.168.1.254"

[network.filter]
link = "up"

[disk-setup]
filesystem = "ext4"

[disk-setup.filter]
removable = "0"
rotational = "0"
min-size = "450G"
max-size = "600G"


[first-boot]
source = "from-url"
ordering = "network-online"
url = "https://raw.githubusercontent.com/buddy9880/pve-unattended-install/main/firstboot.sh"